import { ConnectButton } from '@rainbow-me/rainbowkit'
import type { NextPage } from 'next'
import Head from 'next/head'
import { Counter } from '../components/Counter'
import { Polls } from '../src/components/Polls'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
import Header from '../components/header'
import { Heading } from '@chakra-ui/react'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>ETH-Compatible Private Poll</title>
        <meta
          name="description"
          content="Generated by @rainbow-me/create-rainbowkit"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Header />

        <Heading as='h1' size='xl'>ETH-Compatible Private Poll</Heading>
          <Polls />
      </main>

      <footer className={styles.footer}>
        <a href="https://rainbow.me" target="_blank" rel="noopener noreferrer">
          Made with ❤️ by your frens at 🌈
        </a>
      </footer>
    </div>
  )
}

export default Home
