import { ConnectButton } from '@rainbow-me/rainbowkit'
import type { NextPage } from 'next'
import Head from 'next/head'
import { Counter } from '../components/Counter'
import { Polls } from '../src/components/Polls'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
import Header from '../components/header'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>ETH-Compatible Private Poll</title>
        <meta
          name="description"
          content="Generated by @rainbow-me/create-rainbowkit"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Header />

        <h1 className={styles.title}>ETH-Compatible Private Poll</h1>

        <p className={styles.description}>Add some description</p>

        <div className={styles.section}>
          <Polls />
        </div>

        {/* <div className={styles.card}>
          <Counter/>
        </div>

        <div className={styles.card}>
          Testing
        </div> */}
      </main>

      <footer className={styles.footer}>
        <a href="https://rainbow.me" target="_blank" rel="noopener noreferrer">
          Made with ❤️ by your frens at 🌈
        </a>
      </footer>
    </div>
  )
}

export default Home
