-- CreateTable
CREATE TABLE "Poll" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "title" STRING NOT NULL,
    "groupDescription" STRING NOT NULL,
    "description" STRING NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deadline" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "Poll_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "MerkleTree" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "rootHash" STRING NOT NULL,
    "leaves" STRING[],
    "pollId" INT4 NOT NULL,

    CONSTRAINT "MerkleTree_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "MerkleTree_pollId_key" ON "MerkleTree"("pollId");

-- AddForeignKey
ALTER TABLE "MerkleTree" ADD CONSTRAINT "MerkleTree_pollId_fkey" FOREIGN KEY ("pollId") REFERENCES "Poll"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
